### ISSUE TITLE
Empty link

### ISSUE THREAD

**Issue by resonantdoghouse** [redacademy/play-winter-2018#1]
I know the link is empty because you are using a background image for the logo however you should still have something in the link. You can always use the screen reader text class to hide the text in the link.

e.g. <a href="#"><span class="screen-reader-text">Integrate Play</span></a>

https://github.com/redacademy/play-winter-2018/blob/9fd4614188de64da36c25b56e52a5f824fabdce3/themes/integrate-play/header.php#L31

**Comment by EricChan277** [comment]
@resonantdoghouse can you clarify this issue? Doesen't the href link refer to the home page?

**Comment by rcass** [comment]
You have the link set to the home page, but there is nothing between the opening and closing <a> tags. Aka there is nothing to click on to navigate to the homepage. Usually there would be works there for example.

**Comment by EricChan277** [comment]
Commit link: https://github.com/redacademy/play-winter-2018/commit/88c03b22806f58d40bb859ff1da6e69ef2281cce

**Comment by rcass** [comment]
Looks good 👍
