### ISSUE TITLE
Change from RED_Starter

### ISSUE THREAD

**Issue by rcass** [redacademy/play-winter-2018#10]
https://github.com/redacademy/play-winter-2018/blob/4b5213b02085685f19fda314e4a03ac9a40f3b16/themes/integrate-play/functions.php#L3

**Comment by EricChan277** [comment]
Commit link: https://github.com/redacademy/play-winter-2018/commit/98494eb28f2e7cb4cd1f1fbc20dbac945f79d4fe

Completed!
