### ISSUE TITLE
Google fonts: Make this a single enqueue

### ISSUE THREAD

**Issue by rcass** [redacademy/play-winter-2018#12]
Both google fonts can be called form google together.

So basically these two lines
https://github.com/redacademy/play-winter-2018/blob/4b5213b02085685f19fda314e4a03ac9a40f3b16/themes/integrate-play/functions.php#L92-L93
Can be turn to just one enqueue link

You may just need to pop on over to google fonts to generate a new url to link to that has both typefaces and the appropriate weights.

**Comment by EricChan277** [comment]
Commit link :https://github.com/redacademy/play-winter-2018/commit/3b0e97df7e118369272106fa3235cc4edcc37a4c

Done!

**Comment by rcass** [comment]
looks good 👍
