### ISSUE TITLE
Functions.php Commented Code

### ISSUE THREAD

**Issue by rcass** [redacademy/play-winter-2018#14]
https://github.com/redacademy/play-winter-2018/blob/4b5213b02085685f19fda314e4a03ac9a40f3b16/themes/integrate-play/functions.php#L116-L135

Please delete if you are not using (or if you want to save it for a later project, just save it in a gist).
or if it is something you want to complete just put it in the inc/extras.php (to keep things organized and readable)

**Comment by EricChan277** [comment]
commit link: https://github.com/redacademy/play-winter-2018/commit/a61562b47b57f51645c2ea7f2192e379cfc91995

Done!

**Comment by rcass** [comment]
Looks good 👍
