### ISSUE TITLE
Add document.ready to button.js & integrate-scripts.js

### ISSUE THREAD

**Issue by rcass** [redacademy/play-winter-2018#15]
Wrap your code in a document.ready statement (basically it should come right after making the `$` available.)

Here is more [documentation](https://learn.jquery.com/using-jquery-core/document-ready/) if needed

**Comment by EricChan277** [comment]
Commit link: https://github.com/redacademy/play-winter-2018/commit/d7f5772066ba9b01285062d6410d1882dd43ef88

Done!

**Comment by rcass** [comment]
In the js files you added the document.ready the indentation is a little off. 
Just to promote good quality, just go back and fix it and then this issue will be closed 👍 

(some of the children are not nested properly)

**Comment by EricChan277** [comment]
Commit link: https://github.com/redacademy/play-winter-2018/commit/172b6f4b1036fc048efd99cd03af4cb008c41b5e

Fixed?

**Comment by rcass** [comment]
Yep looks a-ok now 👌
