### ISSUE TITLE
link visited color .btn .purple

### ISSUE THREAD

**Issue by resonantdoghouse** [redacademy/play-winter-2018#16]
When clicking on links with the class .btn .purple the link changes to a visited link which is fine however you are missing some style e.g.   .btn:visited { color: white; }
Currently the link color changes to the same as the background color of the button after clicking on it.

You can see/test this at: http://play.van.cp.academy.red/professional-speaking/

**Comment by jorosafi** [comment]
I think I solved this, but can't be sure until we do another deploy, so I am leaving open for now.

**Comment by rcass** [comment]
Just checked the staging site, this doesn't seem to be resolved
