### ISSUE TITLE
jquery as a dependency

### ISSUE THREAD

**Issue by resonantdoghouse** [redacademy/play-winter-2018#17]
Since your js is using jQuery and you've enqueued jQuery you might as well add it as a dependency by including it in the array e.g.  array('jquery')

https://github.com/redacademy/play-winter-2018/blob/4b5213b02085685f19fda314e4a03ac9a40f3b16/themes/integrate-play/functions.php#L97

**Comment by EricChan277** [comment]
commit link: https://github.com/redacademy/play-winter-2018/commit/f95d0efdb2e4e92dc6a0c6c966ee61f70e01acb7
Done!

**Comment by rcass** [comment]
In the dependancy array, the dependancy has to be listed in quotes. For example ` array('jquery')`

**Comment by EricChan277** [comment]
Link https://github.com/redacademy/play-winter-2018/commit/48c4a4cff0b3378215e050a96992cbf7900b5ee6

**Comment by rcass** [comment]
Looks good 👍
