### ISSUE TITLE
buttons.js

### ISSUE THREAD

**Issue by resonantdoghouse** [redacademy/play-winter-2018#19]
I think I see what you are trying to do here, however it seems that hiding all that content is not the best approach and shouldn't be required to make a modal.

Try appending html with modal styling instead e.g. https://codepen.io/Onomicon/pen/RMaRJg

**Comment by jorosafi** [comment]
@resonantdoghouse using the method in the codepen, how can I prevent the user from scrolling up or down and seeing the rest of the content in the screen? That's the problem I am trying to solve by hiding everything else. If I don't hide it, the user can see content above or below the form. 

I'm also wondering how I can append the form is the form is called using a CFS shortcode in the PHP file.
