### ISSUE TITLE
Mobile: Header not visible when logged in

### ISSUE THREAD

**Issue by rcass** [redacademy/play-winter-2018#21]
![screen shot 2018-03-16 at 2 03 41 pm](https://user-images.githubusercontent.com/5028555/37544777-786b7278-2923-11e8-95a0-09dd2f12d24e.png)

There is a body class called `logged-in` that you can use to apply styles to just when logged in

Th header in desktop, is also cut off when logged into WordPress, so that will need adjustment as well.

**Comment by EricChan277** [comment]
Commit link: https://github.com/redacademy/play-winter-2018/commit/8915ab91db986ec1a9316412479821d96fec7c01

Done!

**Comment by rcass** [comment]
I can't see the issue as resolved on the staging site, so I assume it is just not deployed yet?

**Comment by EricChan277** [comment]
Fixed? : https://github.com/redacademy/play-winter-2018/commit/4744e1a931a1cb57219b04fd5735b98782f99acc

**Comment by EricChan277** [comment]
Ok really fixed now: https://github.com/redacademy/play-winter-2018/commit/49c9a3478eef5976a03f783ceb6e8da87129fb1e
