### ISSUE TITLE
Front-page: Doesn't need to be a template (drop down option)

### ISSUE THREAD

**Issue by rcass** [redacademy/play-winter-2018#22]
![screen shot 2018-03-16 at 2 10 13 pm](https://user-images.githubusercontent.com/5028555/37544879-d609d8ca-2923-11e8-82c2-0d03a6b7d7ec.png)

Since there will only ever just be one front page, there is not need making the front-page as a template (an option you can select).

To remove it from being a template (remove it from the drop down menu), 
just delete this line https://github.com/redacademy/play-winter-2018/blob/4b5213b02085685f19fda314e4a03ac9a40f3b16/themes/integrate-play/front-page.php#L3

**Comment by EricChan277** [comment]
Commit link: https://github.com/redacademy/play-winter-2018/commit/5ef21e12c57f54595a51dadd521f374de63b0d30

Donezo

**Comment by rcass** [comment]
Looks good, just a suggestion but you might want to just add a comment saying it is the template for the front-page, since that is the format you are using for the rest of the template files
