### ISSUE TITLE
Template option: Services

### ISSUE THREAD

**Issue by rcass** [redacademy/play-winter-2018#24]
Not quite sure why but `page-services.php` does not have the same comment block and has been create as template option
![screen shot 2018-03-16 at 2 10 13 pm](https://user-images.githubusercontent.com/5028555/37545161-fbc83420-2924-11e8-98a5-7fd5f7015575.png)

Where as, `page-contact-us.php`, `page-praise.php`, and `page-the-science-of-play.php` all have a similar comment block at the top of the page.

What I recommend is just making services the same as the rest

**Comment by EricChan277** [comment]
Commit link :https://github.com/redacademy/play-winter-2018/commit/ba9378e2be4231315a27d75bae12e5279ad78661

Done!

**Comment by rcass** [comment]
Perfect! Looks great! 👍
