### ISSUE TITLE
Front-page Uppercase

### ISSUE THREAD

**Issue by rcass** [redacademy/play-winter-2018#28]
Remember do not use all caps for works, use CSS to get the desired style.

https://github.com/redacademy/play-winter-2018/blob/18f8072ba19fe072cb07aba0b522822e119d3584/themes/integrate-play/front-page.php#L28-L36

**Comment by EricChan277** [comment]
Sorry, I don't know when the change was made but its fixed

**Comment by rcass** [comment]
Ok, well as long as it is fixed I suppose 🤷‍♀️
