### ISSUE TITLE
Function.php Code Organization

### ISSUE THREAD

**Issue by rcass** [redacademy/play-winter-2018#29]
Reminder: the reason we have the includes folder is to better organize the functions.php so it doesn't get crazy long and unmanageable.

Best to take this code
https://github.com/redacademy/play-winter-2018/blob/18f8072ba19fe072cb07aba0b522822e119d3584/themes/integrate-play/functions.php#L127-L165

And move it to the extras.php file (inc/extras.php)

**Comment by EricChan277** [comment]
Commit link : https://github.com/redacademy/play-winter-2018/commit/146a3f0d67f8a2e66b1c085d6fa968c1973e83b9
