### ISSUE TITLE
Duplicate #id

### ISSUE THREAD

**Issue by resonantdoghouse** [redacademy/play-winter-2018#3]
It looks like you have the id of 'navigation' used both in the header and footer.

https://github.com/redacademy/play-winter-2018/blob/9fd4614188de64da36c25b56e52a5f824fabdce3/themes/integrate-play/footer.php#L13

https://github.com/redacademy/play-winter-2018/blob/9fd4614188de64da36c25b56e52a5f824fabdce3/themes/integrate-play/header.php#L39

**Comment by EricChan277** [comment]
Commit link: https://github.com/redacademy/play-winter-2018/commit/6556f7b8e8ac10b94976d16b6439687fd5791d2e

Thanks!

**Comment by rcass** [comment]
Looks good
