### ISSUE TITLE
Sizzle Reel button not working

### ISSUE THREAD

**Issue by jorosafi** [redacademy/play-winter-2018#30]
Opening this issue so we don't forget to fix it. 

I tried to see why it isn't working, but can't figure it out. The hover event is not happening, and nothing happens on click. 

It's as if it's being covered by an invisible element that prevents the mouse from getting to it. I tried increasing the z-index, but that didn't work. I also tried to move it to a different position, but that didn't work either.

**Comment by EricChan277** [comment]
Commit link: 17f4653d2dc26f7054b520fbf9f08f8098901f50
