### ISSUE TITLE
Mobile: Adding Padding to <a> to increase clickable area

### ISSUE THREAD

**Issue by rcass** [redacademy/play-winter-2018#4]
On mobile the footer links, the click/tappable areas need to be increased. The tappable area is quite small considering people with be tapping via their fingers.

![screen shot 2018-03-16 at 1 19 55 pm](https://user-images.githubusercontent.com/5028555/37542894-ef661b78-291c-11e8-996d-7b02ee9dbb25.png)

Basically you need to add more padding to the anchor tags. You may need to adjust the other padding settings, but it would result in the tappable area being larger.

**Comment by EricChan277** [comment]
Commit link: https://github.com/redacademy/play-winter-2018/commit/755d954abe9d6b977947f9cc9ee4688ae519925b

Completed!
