### ISSUE TITLE
html commented out php

### ISSUE THREAD

**Issue by resonantdoghouse** [redacademy/play-winter-2018#6]
This doesn't seem to break anything but commenting out php blocks with html comments isn't always great. 

A better way would be to comment out the php code using // /* */ # etc...

<?php
// if ( have_posts() ) :
?>
<?php 
// if( is_home() && ! is_front_page() ) :
?>

<?php
// endif;
?>

https://github.com/redacademy/play-winter-2018/blob/4b5213b02085685f19fda314e4a03ac9a40f3b16/themes/integrate-play/front-page.php#L20

**Comment by cchan54** [comment]
comment has been removed

**Comment by rcass** [comment]
Okay looks good 👍
